{
 "title": "Weather Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "GET Weather International",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "weather_requests_total{exported_endpoint=\"getWeatherInternational\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERR: GET Weather International",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_requests_total{exported_endpoint=\"/weather/:location\", status=\"Internal Server Error\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"default\", pod=\"weather-76b6cccb5c-pb66t\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEM Usage MB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"default\", pod=\"weather-76b6cccb5c-pb66t\"}/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network TX Kbps",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_network_transmit_bytes_total{namespace=\"default\", pod=\"weather-76b6cccb5c-pb66t\"}[5m])/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Network RX MB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_network_receive_bytes_total{namespace=\"default\", pod=\"weather-76b6cccb5c-pb66t\"}[5m])/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET Weather Local",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "weather_requests_total{exported_endpoint=\"getWeatherLocal\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webserver Stress Test",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "http_requests_total{exported_endpoint=\"/weather/stress0\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}