apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: weather-monitor
  labels:
    release: prometheus-operator  # Must match your Prometheus release name
spec:
  namespaceSelector:
    matchNames:
      - default 
  selector:
    matchLabels:
      app: weather
  endpoints:
    - port: http
      path: /metrics
      interval: 2s

