apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weather.fullname" . }}
  labels:
    app: {{ .Values.labels.app }}
    release: {{ .Values.labels.release }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          {{- if .Values.openTelemetry.enabled }}
          env:
            {{- range $key, $value := .Values.openTelemetry.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          {{- end }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
        {{- if .Values.openTelemetry.collectorSidecar.enabled }}
        - name: otel-collector
          image: {{ .Values.openTelemetry.collectorSidecar.image }}
          args:
            - "--config=/etc/otel-collector-config.yaml"
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
            - containerPort: 14250
              name: jaeger-grpc
            - containerPort: 8889
              name: prometheus
          volumeMounts:
            - name: otel-collector-config
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
          resources:
            requests:
              cpu: {{ .Values.openTelemetry.collectorSidecar.resources.requests.cpu }}
              memory: {{ .Values.openTelemetry.collectorSidecar.resources.requests.memory }}
            limits:
              cpu: {{ .Values.openTelemetry.collectorSidecar.resources.limits.cpu }}
              memory: {{ .Values.openTelemetry.collectorSidecar.resources.limits.memory }}
        {{- end }}
      {{- if .Values.openTelemetry.collectorSidecar.enabled }}
      volumes:
        - name: otel-collector-config
          configMap:
            name: {{ include "weather.fullname" . }}-otel-collector-config
      {{- end }}

