apiVersion: v1
kind: Service
metadata:
  name: {{ include "weather.fullname" . }}
  labels:
    app: {{ .Values.labels.app }}
    release: {{ .Values.labels.release }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    - name: metrics
      port: 8082
      targetPort: 8082
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: prometheus-exporter
      port: 8889
      targetPort: 8889
      protocol: TCP

