# jaeger-allinone.yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:latest
    options:
      collector:
        otlp:
          enabled: true
          grpc:
            host-port: 4317
          http:
            host-port: 4318
      log-level: info
  storage:
    type: memory
  ingress:
    enabled: true
