# values.yaml
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'otel-collector'
        scrape_interval: 5s
        static_configs:
          - targets: ['weather-service.default.svc.cluster.local:8082']
        metrics_path: '/metrics'
