# values.yaml
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'otel-collector'
        scrape_interval: 1s
        static_configs:
          - targets: ['weather-service.default.svc.cluster.local:8889']
        metrics_path: /metrics

